<a href="https://colab.research.google.com/github/Sourav-Alakkadan/TASK5/blob/master/ANN2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
import pandas as pd
import seaborn as sns
df=pd.read_csv('/content/Churn_Modelling.csv')
df

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [ ]:
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [ ]:
df.tail()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [ ]:
df.isna().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [ ]:
df.drop(['RowNumber','CustomerId','Surname'],axis=1,inplace=True)
df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [ ]:
df['Gender']=df['Gender'].map({'Male':1,'Female':0})

In [ ]:
#df1=pd.get_dummies(df['Geography'],drop_first=True)

In [ ]:
# df2=pd.concat([df,df1])
# df2

In [ ]:
df['Geography']=df['Geography'].map({'France':0,'Spain':1,'Germany':2})
df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,0,0,42,2,0.00,1,1,1,101348.88,1
1,608,1,0,41,1,83807.86,1,0,1,112542.58,0
2,502,0,0,42,8,159660.80,3,1,0,113931.57,1
3,699,0,0,39,1,0.00,2,0,0,93826.63,0
4,850,1,0,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,0,1,39,5,0.00,2,1,0,96270.64,0
9996,516,0,1,35,10,57369.61,1,1,1,101699.77,0
9997,709,0,0,36,7,0.00,1,0,1,42085.58,1
9998,772,2,1,42,3,75075.31,2,1,0,92888.52,1
9999,792,0,0,28,4,130142.79,1,1,0,38190.78,0

In [ ]:
x=df.iloc[:,:-1].values
x

array([[6.1900000e+02, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        1.0000000e+00, 1.0134888e+05],
       [6.0800000e+02, 1.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 1.1254258e+05],
       [5.0200000e+02, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 1.1393157e+05],
       ...,
       [7.0900000e+02, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 4.2085580e+04],
       [7.7200000e+02, 2.0000000e+00, 1.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 9.2888520e+04],
       [7.9200000e+02, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 3.8190780e+04]])

In [ ]:
y=df.iloc[:,-1].values
y

array([1, 0, 1, ..., 1, 1, 0])

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=42)

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scaler.fit(x_train)
x_train=scaler.transform(x_train)
x_test=scaler.transform(x_test)

In [ ]:
ann=tf.keras.models.Sequential()

In [ ]:
ann.add(tf.keras.layers.Dense(6,activation='relu'))

In [ ]:
ann.add(tf.keras.layers.Dense(6,activation='relu'))

In [ ]:
ann.add(tf.keras.layers.Dense(6,activation='sigmoid'))

In [ ]:
ann.add(tf.keras.layers.Dense(1,activation='relu'))

In [ ]:
ann.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [ ]:
ann.fit(x_train,y_train,batch_size=100,epochs=50)

Epoch 1/50
70/70 [==============================] - 3s 4ms/step - loss: 0.5648 - accuracy: 0.7794
Epoch 2/50
70/70 [==============================] - 0s 3ms/step - loss: 0.5222 - accuracy: 0.7924
Epoch 3/50
70/70 [==============================] - 0s 3ms/step - loss: 0.5020 - accuracy: 0.7916
Epoch 4/50
70/70 [==============================] - 0s 3ms/step - loss: 0.4861 - accuracy: 0.7909
Epoch 5/50
70/70 [==============================] - 0s 3ms/step - loss: 0.4752 - accuracy: 0.7934
Epoch 6/50
70/70 [==============================] - 0s 3ms/step - loss: 0.4685 - accuracy: 0.7946
Epoch 7/50
70/70 [==============================] - 0s 3ms/step - loss: 0.4607 - accuracy: 0.7979
Epoch 8/50
70/70 [==============================] - 0s 3ms/step - loss: 0.4558 - accuracy: 0.8004
Epoch 9/50
70/70 [==============================] - 0s 3ms/step - loss: 0.4512 - accuracy: 0.8013
Epoch 10/50
70/70 [==============================] - 0s 3ms/step - loss: 0.4583 - accuracy: 0.8030
Epoch 11/50
70/70 [==============================] - 0s 3ms/step - loss: 0.4472 - accuracy: 0.8024
Epoch 12/50
70/70 [==============================] - 0s 3ms/step - loss: 0.4447 - accuracy: 0.8024
Epoch 13/50
70/70 [==============================] - 0s 3ms/step - loss: 0.4443 - accuracy: 0.8030
Epoch 14/50
70/70 [==============================] - 0s 3ms/step - loss: 0.4402 - accuracy: 0.8026
Epoch 15/50
70/70 [==============================] - 0s 3ms/step - loss: 0.4375 - accuracy: 0.8039
Epoch 16/50
70/70 [==============================] - 0s 2ms/step - loss: 0.4350 - accuracy: 0.8027
Epoch 17/50
70/70 [==============================] - 0s 3ms/step - loss: 0.4324 - accuracy: 0.8021
Epoch 18/50
70/70 [==============================] - 0s 3ms/step - loss: 0.4308 - accuracy: 0.8033
Epoch 19/50
70/70 [==============================] - 0s 3ms/step - loss: 0.4273 - accuracy: 0.8047
Epoch 20/50
70/70 [==============================] - 0s 2ms/step - loss: 0.4247 - accuracy: 0.8066
Epoch 21/50
70/70 [==============================] - 0s 2ms/step - loss: 0.4210 - accuracy: 0.8051
Epoch 22/50
70/70 [==============================] - 0s 3ms/step - loss: 0.4177 - accuracy: 0.8064
Epoch 23/50
70/70 [==============================] - 0s 2ms/step - loss: 0.4142 - accuracy: 0.8083
Epoch 24/50
70/70 [==============================] - 0s 3ms/step - loss: 0.4108 - accuracy: 0.8087
Epoch 25/50
70/70 [==============================] - 0s 2ms/step - loss: 0.4070 - accuracy: 0.8127
Epoch 26/50
70/70 [==============================] - 0s 3ms/step - loss: 0.4042 - accuracy: 0.8146
Epoch 27/50
70/70 [==============================] - 0s 3ms/step - loss: 0.4003 - accuracy: 0.8189
Epoch 28/50
70/70 [==============================] - 0s 3ms/step - loss: 0.3995 - accuracy: 0.8213
Epoch 29/50
70/70 [==============================] - 0s 3ms/step - loss: 0.4090 - accuracy: 0.8249
Epoch 30/50
70/70 [==============================] - 0s 3ms/step - loss: 0.4119 - accuracy: 0.8246
Epoch 31/50
70/70 [==============================] - 0s 3ms/step - loss: 0.3959 - accuracy: 0.8267
Epoch 32/50
70/70 [==============================] - 0s 3ms/step - loss: 0.3910 - accuracy: 0.8317
Epoch 33/50
70/70 [==============================] - 0s 3ms/step - loss: 0.3897 - accuracy: 0.8336
Epoch 34/50
70/70 [==============================] - 0s 3ms/step - loss: 0.3871 - accuracy: 0.8344
Epoch 35/50
70/70 [==============================] - 0s 3ms/step - loss: 0.3857 - accuracy: 0.8379
Epoch 36/50
70/70 [==============================] - 0s 3ms/step - loss: 0.3854 - accuracy: 0.8386
Epoch 37/50
70/70 [==============================] - 0s 3ms/step - loss: 0.3825 - accuracy: 0.8376
Epoch 38/50
70/70 [==============================] - 0s 3ms/step - loss: 0.3805 - accuracy: 0.8377
Epoch 39/50
70/70 [==============================] - 0s 3ms/step - loss: 0.3793 - accuracy: 0.8391
Epoch 40/50
70/70 [==============================] - 0s 3ms/step - loss: 0.3780 - accuracy: 0.8377
Epoch 41/50
70/70 [==============================] - 0s 4ms/step - loss: 0.3775 - accuracy: 0.8383
Epoch 42/50
70/70 [==============================] - 0s 4ms/step - loss: 0.3772 - accuracy: 0.8374
Epoch 43/50
70/70 [==============================] - 0s 4ms/step - loss: 0.3773 - accuracy: 0.8393
Epoch 44/50
70/70 [==============================] - 0s 4ms/step - loss: 0.3751 - accuracy: 0.8399
Epoch 45/50
70/70 [==============================] - 0s 4ms/step - loss: 0.3741 - accuracy: 0.8404
Epoch 46/50
70/70 [==============================] - 0s 4ms/step - loss: 0.3719 - accuracy: 0.8396
Epoch 47/50
70/70 [==============================] - 0s 4ms/step - loss: 0.3742 - accuracy: 0.8417
Epoch 48/50
70/70 [==============================] - 0s 4ms/step - loss: 0.3743 - accuracy: 0.8399
Epoch 49/50
70/70 [==============================] - 0s 4ms/step - loss: 0.3739 - accuracy: 0.8400
Epoch 50/50
70/70 [==============================] - 0s 4ms/step - loss: 0.3704 - accuracy: 0.8400

In [ ]:
pred=ann.predict(scaler.transform([x_train[6]]))
if(pred>0.5):
  print(1)
else:
  print(0)

1/1 [==============================] - 0s 77ms/step
0

In [ ]:
ann.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 6)                 66

 dense_1 (Dense)             (None, 6)                 42

 dense_2 (Dense)             (None, 6)                 42

 dense_3 (Dense)             (None, 1)                 7

=================================================================
Total params: 157 (628.00 Byte)
Trainable params: 157 (628.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________